# Generated by Django 3.1 on 2020-08-16 11:23

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=15)),
                ('about_me', models.TextField(max_length=500)),
                ('profile_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile-images/')),
                ('stripe_customer_id', models.CharField(max_length=50)),
                ('is_job_seeker', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('plan_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plans')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('languages', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('English', 'English'), ('Mandarin Chinese', 'Mandarin Chinese'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('French', 'French'), ('Arabic', 'Arabic'), ('Bengali', 'Bengali'), ('Russian', 'Russian'), ('Portuguese', 'Portuguese'), ('Indonesian', 'Indonesian'), ('Other', 'Other')], max_length=96)),
                ('coding_languages', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Java', 'Java'), ('PHP', 'PHP'), ('C#', 'C#'), ('C++', 'C++'), ('TypeScript', 'TypeScript'), ('Shell', 'Shell'), ('C', 'C'), ('Ruby', 'Ruby'), ('Other', 'Other')], max_length=63)),
                ('frameworks', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ruby on Rails', 'Ruby on Rails'), ('Symfony', 'Symfony'), ('Angular JS', 'Angular JS'), ('React.js', 'React.js'), ('Cake PHP', 'Cake PHP'), ('Asp.net', 'Asp.net'), ('Node.js', 'Node.js'), ('Yii Framework', 'Yii Framework'), ('Meteor', 'Meteor'), ('Laravel', 'Laravel'), ('Ember', 'Ember'), ('Django', 'Django'), ('Express.js', 'Express.js'), ('Spring', 'Spring'), ('Flask', 'Flask'), ('Active Server Pages', 'Active Server Pages'), ('jQuery', 'jQuery'), ('CodeIgniter', 'CodeIgniter'), ('Drupal', 'Drupal'), ('Bootstrap', 'Bootstrap')], max_length=188)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('experience_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.jobseekerprofile')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_address1', models.CharField(max_length=50)),
                ('company_address2', models.CharField(blank=True, max_length=50)),
                ('company_city', models.CharField(max_length=50)),
                ('company_ZIP', models.CharField(blank=True, max_length=50)),
                ('company_state', models.CharField(max_length=50)),
                ('company_country', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('education_institute', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('education_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.jobseekerprofile')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
    ]
