# Generated by Django 3.1 on 2020-08-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_job',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
