# Generated by Django 3.0.8 on 2020-08-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile-images/'),
        ),
    ]
