# Generated by Django 3.1 on 2020-09-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_jobseekerprofile_preferred_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='profile-images/', verbose_name=''),
        ),
    ]
