# Generated by Django 3.0.8 on 2020-08-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200802_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding_languages', models.CharField(blank=True, choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Java', 'Java'), ('PHP', 'PHP'), ('C#', 'C#'), ('C++', 'C++'), ('TypeScript', 'TypeScript'), ('Shell', 'Shell'), ('C', 'C'), ('Ruby', 'Ruby'), ('Other', 'Other')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(blank=True, choices=[('English', 'English'), ('Mandarin Chinese', 'Mandarin Chinese'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('French', 'French'), ('Arabic', 'Arabic'), ('Bengali', 'Bengali'), ('Russian', 'Russian'), ('Portuguese', 'Portuguese'), ('Indonesian', 'Indonesian'), ('Other', 'Other')], max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='coding_languages',
            field=models.ManyToManyField(blank=True, to='profiles.CodingLanguages'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='profiles.Languages'),
        ),
    ]
