# Generated by Django 3.1 on 2020-09-13 12:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='coding_languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Java', 'Java'), ('PHP', 'PHP'), ('C#', 'C#'), ('C++', 'C++'), ('TypeScript', 'TypeScript'), ('Shell', 'Shell'), ('C', 'C'), ('Ruby', 'Ruby'), ('Other', 'Other')], max_length=63),
        ),
        migrations.AddField(
            model_name='jobs',
            name='frameworks',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ruby on Rails', 'Ruby on Rails'), ('Symfony', 'Symfony'), ('Angular JS', 'Angular JS'), ('React.js', 'React.js'), ('Cake PHP', 'Cake PHP'), ('Asp.net', 'Asp.net'), ('Node.js', 'Node.js'), ('Yii Framework', 'Yii Framework'), ('Meteor', 'Meteor'), ('Laravel', 'Laravel'), ('Ember', 'Ember'), ('Django', 'Django'), ('Express.js', 'Express.js'), ('Spring', 'Spring'), ('Flask', 'Flask'), ('Active Server Pages', 'Active Server Pages'), ('jQuery', 'jQuery'), ('CodeIgniter', 'CodeIgniter'), ('Drupal', 'Drupal'), ('Bootstrap', 'Bootstrap')], max_length=188),
        ),
        migrations.AddField(
            model_name='jobs',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('English', 'English'), ('Mandarin Chinese', 'Mandarin Chinese'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('French', 'French'), ('Arabic', 'Arabic'), ('Bengali', 'Bengali'), ('Russian', 'Russian'), ('Portuguese', 'Portuguese'), ('Indonesian', 'Indonesian'), ('Other', 'Other')], max_length=96),
        ),
    ]
