# Generated by Django 3.1 on 2020-08-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('Jobseeker plan', 'Jobseeker plan'), ('Recruiter plan', 'Recruiter plan')], default='Jobseeker plan', max_length=50)),
                ('price', models.IntegerField(default=25)),
                ('stripe_pricing_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlanSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
