# Generated by Django 3.1 on 2020-08-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscription',
            name='recruiter_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.recruiterprofile'),
        ),
    ]
